Add controllers
dmmitr632/java-shareit pull request #1
Opened 2023-01-28 22:56 UTC by dmmitr632

2023-01-30 09:39 UTC, alexache requested changes

2023-01-30 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/FavIconController.java
> +@Component
@Controller и есть разновидность @Component, получается дублирование

2023-01-30 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        itemList.forEach(item -> itemDtoList.add(ItemMapper.toItemDto(item)));
(опционально) в функциональном стиле будет нагляднее с return itemList.stream().map(ItemMapper::toItemDto).collect(Collectors.toList());

2023-01-30 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>      private Integer request;
Это по сути requestId, а не request?

2023-01-30 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Integer owner;
Это должны быть объекты User owner, ItemRequest request

2023-01-30 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +public class ItemService {
Желательно для всех сервисов выделить интерфейс ItemService, а реализацию перенести в ItemServiceImpl

2023-01-30 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (userStorage.getUserById(userId) != null)
Немного лишняя проверка из-за того, что getUserById и так бросает исключение, если пользователь не найден

2023-01-30 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (itemStorage.getItemById(itemId) != null && userStorage.getUserById(userId) != null) {
getItemById() и getUserById() вызывался в начале метода, к чему повторное дублирование?

2023-01-30 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageInMemory.java
> +        if (items.containsKey(itemId)) {
(опционально) В целом для всех условий-циклов лучше придерживаться единого код стиля с фигурными скобками, даже если в блоке будет единственный операнд

2023-01-30 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageInMemory.java
> +            if (item.getOwner() == id) foundItems.add(item);
(опционально) Это можно упростить, если завести дополнительную мапу юзеров на их товары

2023-01-30 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageInMemory.java
> +        for (Item item : items.values()) {
text.toLowerCase() лучше вызывать единожды до начала цикла

2023-01-30 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    int id;
Не хватает модификаторов доступа у полей

2023-01-30 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageInMemory.java
> +        if (user.isPresent() && user.orElse(null).getId() != userId) {
user.orElse(null).getId() выглядит довольно странно

2023-01-30 13:53 UTC, dmmitr632 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>      private Integer request;
ага

2023-01-30 13:55 UTC, dmmitr632 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Integer owner;
А это обязательно переделывать? Разве обращения по id недостаточно?

2023-01-30 13:56 UTC, dmmitr632 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (itemStorage.getItemById(itemId) != null && userStorage.getUserById(userId) != null) {
наверное случайно, у меня пару раз тесты в постмане не проходились

2023-01-30 14:11 UTC, dmmitr632 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Integer owner;
Вообще в БД же по id ссылаются всегда на другую таблицу

2023-02-01 18:40 UTC, alexache approved these changes

2023-02-01 18:40 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +
Много лишних пустых строк, это противоречит стайл гайду

2023-02-01 18:42 UTC, merged