Add item requests
dmmitr632/java-shareit pull request #3
Opened 2023-02-11 09:38 UTC by dmmitr632

2023-02-13 22:24 UTC, alexache requested changes

2023-02-13 22:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/FavIconController.java
> +        // disables favicon warning
Будет довольно сложно придумать тест на этот класс-метод. Точнее, не так уж сложно, сколько имеет мало смысла

2023-02-13 22:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            // подтвержденной
Огонь

2023-02-13 22:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +// @Value
Закомментированный код лучше удалять

2023-02-13 22:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    public static ItemShort toItemShort(ItemDto itemDto) {
Если эти методы только для тестов, то их не должно быть в основном коде

2023-02-13 22:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (size == null) {
Может лучше на уровне контроллера сделать значение по умолчанию?

2023-02-13 22:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getBooker().getId().intValue() == booking.getItem().getOwner().getId().intValue()) {
Отчего не просто через equals? booking.getBooker().getId().equals(... )

2023-02-13 22:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public Item(int id, String name, String description, Boolean available, User owner) {
(вопрос) А для чего конструктор, если есть билдер?

2023-02-13 22:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageInMemory.java
> +        } else {
(опционально) Можно уже и избавиться от этих стораджей

2023-02-13 22:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/model/Request.java
> +//    @Override
Закомментированный код лучше удалять

2023-02-13 22:24 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +                        userId, Pageable.ofSize(from + size)).stream()
Pageable.ofSize(from + size)) выглядит неверным, как с этим начинать не с первой страницы?

2023-02-13 22:24 UTC, alexache commented on src/main/resources/application.properties
> +#
А зачем это комментить?

2023-02-13 22:24 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    User booker = new User(null, "Booker", "booker@google.com");
Модификаторы доступа полей

2023-02-13 22:24 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +class BookingServiceTest {
Судя по тому, что здесь мокается сервис, это больше похоже на BookingControllerTest

2023-02-13 22:24 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    }
Хорошо бы еще напоследок добавлять валидацию через verify()

2023-02-14 01:03 UTC, dmmitr632 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getBooker().getId().intValue() == booking.getItem().getOwner().getId().intValue()) {
Я сделал вначале через Object.equals, но у меня вылезала ошибка при тестах на ГитХабе. https://github.com/dmmitr632/java-shareit/pull/3/commits/5cfb519da8a476a4f8db41a7d24aa9597194c12b

2023-02-14 01:09 UTC, dmmitr632 commented on src/main/resources/application.properties
> +#
На ГитХабе тесты проходятся только с h2, а у меня на компьютере наоборот, только с Postgres.
В файле db1.properties параметры Postgres.

2023-02-14 01:15 UTC, dmmitr632 commented on src/main/java/ru/practicum/shareit/FavIconController.java
> +        // disables favicon warning
Процент покрытия тестов учитывает все классы и все методы? Т.е все не слишком нужное стоит удалить, чтобы не писать лишние тесты?

2023-02-15 19:37 UTC, alexache commented on src/main/java/ru/practicum/shareit/FavIconController.java
> +        // disables favicon warning
Да. Это такая бритва Оккамы - классы должны быть востребованными и покрытыми тестами

2023-02-15 20:08 UTC, alexache requested changes

2023-02-15 20:08 UTC, alexache commented on pom.xml
> +        <dependency>
а для чего плагины в зависимостях? у них свои секции

2023-02-15 20:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/error/ErrorResponse.java
> +//    public ErrorResponse(String error) {
Закомментированный код нужно удалять

2023-02-15 20:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                        commentRepository.findAllByItem_id(item.getId()))))
Это запрос к базе в цикле - такого не должно быть. Нужно отдельно запросить все комментарии  по списку вещей

2023-02-15 20:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/dto/RequestDto.java
>      Integer id;
После того, как это перестало быть Value -  нужно вернуть модификаторы доступа полей

2023-02-15 20:08 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper objectMapper = JsonMapper.builder()
Модификатор доступа потерялся

2023-02-15 20:08 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerUnitTest.java
> +        assertEquals(booking, booking);
ЧТо это за проверки равенста объекта на самого себя?

2023-02-15 20:08 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerUnitTest.java
> +public class BookingControllerUnitTest {
Название как-то не соответствует, больше похоже на интеграционный тест

2023-02-15 20:08 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +class BookingServiceImplTest {
Почему он пустой?

2023-02-15 20:08 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemControllerUnitTest.java
> +public class ItemControllerUnitTest {
Тоже проблема с названием

2023-02-15 20:08 UTC, alexache commented on src/test/java/ru/practicum/shareit/user/repository/UserRepositoryTest.java
> +    UserRepository userRepository;
Модификаторы доступа

2023-02-16 00:22 UTC, dmmitr632 commented on pom.xml
> +        <dependency>
Мне пришлось воспроизвести почти все зависимости, чтобы посмотреть процент покрытия кода. Но конкретно эту вроде просто парсер.

2023-02-16 00:29 UTC, dmmitr632 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerUnitTest.java
> +        assertEquals(booking, booking);
У меня была проблема с процентами code coverage, jococo проверяет каждую строчку. В том числе и строчки из equals и hashcode. Без проверки засчитывается минус к проценту, сейчас у меня 91%, минимум 90%.

2023-02-16 00:31 UTC, dmmitr632 commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +class BookingServiceImplTest {
забыл удалить

2023-02-16 00:54 UTC, dmmitr632 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                        commentRepository.findAllByItem_id(item.getId()))))
см. Пачку

2023-02-16 01:30 UTC, dmmitr632 commented on pom.xml
> +        <dependency>
В idea и jacoco процент покрытия кода сильно отличается

2023-02-16 07:39 UTC, dmmitr632 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                        commentRepository.findAllByItem_id(item.getId()))))
Я мб неверно понимаю map()

2023-02-16 07:48 UTC, dmmitr632 commented on src/test/java/ru/practicum/shareit/item/ItemControllerUnitTest.java
> +public class ItemControllerUnitTest {
а как тогда его лучше назвать?

2023-02-17 00:04 UTC, alexache approved these changes

2023-02-17 00:04 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    List<Comment> putCommentsInItem(List<Comment> comments, int itemId) {
(опционально) Все это легко заменяется стримом и фильтром

2023-02-17 00:04 UTC, alexache commented on src/test/java/ru/practicum/shareit/request/RequestControllerAssertTest.java
> +        Request request = RequestMapper.toRequestWithoutItems(requestDto, UserMapper.toUser(userDto1)
больше похоже на тест на маппер, который может быть отдельно

2023-02-17 21:35 UTC, merged